export enum ActionTypes {
  GET_ALL_SERVICES = "GET_ALL_SERVICES",
  GET_SERVICE = "GET_SERVICE",
  ADD_SERVICE = "ADD_SERVICE",
  DELETE_SERVICE = "DELETE_SERVICE",
  STOP_SERVICE = "STOP_SERVICE",
  START_SERVICE = "START_SERVICE",
  CONNECT = "CONNECT",
  DISCONNECT = "DISCONNECT",
}
