export enum MutationTypes {
  SET_SERVICES = "SET_SERVICES",
  ADD_SERVICE = "ADD_MESSAGE",
  DELETE_SERVICE = "DELETE_MESSAGE",
  SERVICE_STOPPED = "SERVICE_STOPPED",
  SERVICE_STARTED = "SERVICE_STARTED",
  CONNECT = "CONNECT",
  DISCONNECT = "DISCONNECT",
}
